settings:
  title: 'Status Page'
  url: 'https://ghstatuspage.it-042.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 31 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-site # unique identifier
    name: Diamond Tours
    description: 'Primary Website' # default=empty
    url: 'https://www.diamondtours.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: gtcom
    name: Group Trips
    description: ''
    url: 'https://www.grouptrips.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: travelconfident
    name: Travel Confident
    description: ''
    url: 'https://www.travelconfident.com/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: dtsurvey
    name: Diamond Tours Survey
    url: 'https://www.dtsurvey.com/'

  - id: int-guac # unique identifier
    name: Internal Guacamole
    description: 'Internal Guacamole' # default=empty
    url: 'https://g.dtcorp.com/guacamole/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ext-guac # unique identifier
    name: External Guacamole
    description: 'External Guacamole' # default=empty
    url: 'https://g2.dtcorp.com/guacamole/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: dtexternal
    name: Extranet
    description: 'Authelia'
    url: 'https://dtexternal.diamondtours.net/'
    method: GET
    expectedStatus: 200
    followRedirect: true
    linkable: true
